HAI
	BTW LOLCODE SAMPLE 4:
	
	I HAS A NUM
	VISIBLE "Enter number: "
	GIMMEH NUM
	
	BOTH SAEM NUM AN 0
	O RLY?
		YA RLY
			NUM R "ZERO"
		MEBBE BOTH SAEM NUM AN SMALLR OF NUM AN 50
			NUM R "LESS THAN OR EQUAL TO 50"
		NO WAI
			NUM R "GREATER THAN 50"
	OIC
	
	VISIBLE "Your input number is " NUM
KTHXBYE
